name: dive
channels:
  - nvidia/label/cuda-11.8.0
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - cuda-toolkit
  - pip
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - lightning==2.5.2
      - numpy==2.2.6
      - scipy
      - pandas
      - matplotlib
      - seaborn
      - h5py
      - tensorboard
      - torchviz
      - pymap3d
      - git+https://github.com/decargroup/navlie.git